name: SynCinema
description: "SynCinema is a cross-platform Flutter app for synchronized movie watching with friends, featuring a modern glassmorphism UI, chat, reactions, and spoiler support. Enjoy seamless movie nights together, no matter where you are!"
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  socket_io_client: ^2.0.3+1
  video_player: ^2.8.1
  chewie: ^1.7.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#000000"
